name: Build
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  build-package:
    name: Build Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Cache Dependencies
        uses: actions/cache@v3.3.2
        with:
          path: .yarn
          key: yarn-${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Install Dependencies
        run: corepack enable && yarn install

      - name: Check Package
        run: yarn check && git diff --exit-code HEAD

      - name: Create Package
        run: yarn pack

      - name: Upload Package as Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          path: package.tgz

  generate-docs:
    name: Generate Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Cache Dependencies
        uses: actions/cache@v3.3.2
        with:
          path: .yarn
          key: yarn-${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Install Dependencies
        run: corepack enable && yarn install

      - name: Generate Documentation
        run: yarn doc
