name: Build
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  build-package:
    name: Build Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 20

      - name: Install Dependencies
        uses: threeal/yarn-install-action@v1.0.0

      - name: Create Package
        run: corepack yarn pack

      - name: Upload Package as Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          path: package.tgz

  generate-docs:
    name: Generate Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 20

      - name: Install Dependencies
        uses: threeal/yarn-install-action@v1.0.0

      - name: Generate Documentation
        run: corepack yarn doc
