name: Deploy
on:
  workflow_dispatch:
  push:
    branches: [main]
jobs:
  generate-docs:
    name: Generate Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Cache Dependencies
        uses: actions/cache@v3.3.2
        with:
          path: .yarn
          key: yarn-${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Install Dependencies
        run: corepack enable && yarn install

      - name: Generate Documentation
        run: yarn doc

      - name: Upload Documentation as Pages
        uses: actions/upload-pages-artifact@v2.0.0
        with:
          path: docs

  deploy-pages:
    name: Deploy Pages
    needs: generate-docs
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    concurrency:
      group: pages
      cancel-in-progress: false
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v3.0.6

      - name: Deploy Pages
        id: deployment
        uses: actions/deploy-pages@v2.0.4
