name: deploy
on:
  workflow_dispatch:
  push:
    branches: [main]
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: pages
  cancel-in-progress: false
jobs:
  docs:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Setup Pages
        uses: actions/configure-pages@v3.0.6

      - name: Setup Node.js
        uses: actions/setup-node@v3.7.0
        with:
          node-version: latest

      - name: Setup Yarn
        run: |
          corepack enable
          corepack prepare yarn@stable --activate

      - name: Cache deps
        uses: actions/cache@v3.3.1
        with:
          path: .yarn
          key: yarn-${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Install deps
        run: yarn install

      - name: Generate docs
        run: yarn doc

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2.0.0
        with:
          path: docs

      - name: Deploy Pages
        id: deployment
        uses: actions/deploy-pages@v2.0.4
