name: test
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  lib:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [windows, ubuntu, macos]
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Install deps
        run: yarn install

      - name: Test lib
        run: yarn test

      - name: Check diff
        run: git diff --exit-code HEAD
